<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.2.12deb2+deb8u1 setup script
 * Date: Fri, 22 Jan 2016 07:24:14 +0000
 */

/* Servers configuration */
if(!isset($i)) {
  $i = count($cfg['Servers']);
}

$i = 0;
/* Servers */
foreach(array_filter(array_map(function($h) { return trim($h); }, explode(",", getenv("MYSQL_SERVERS"))))
  as $dbHost) {
  $i++;
  $cfg['Servers'][$i] = array();
  $cfg['Servers'][$i]['verbose'] = '';  
  $cfg['Servers'][$i]['host'] = $dbHost;
  $cfg['Servers'][$i]['port'] = '';  
  $cfg['Servers'][$i]['socket'] = '';
  $cfg['Servers'][$i]['connect_type'] = 'tcp';
  $cfg['Servers'][$i]['nopassword'] = true;   
  $cfg['Servers'][$i]['auth_type'] = 'cookie';
  $cfg['Servers'][$i]['user'] = 'root';
  $cfg['Servers'][$i]['password'] = '';
}
/* End of servers configuration */
$cfg['blowfish_secret'] = md5(gethostname()); // simply use container id as blowfish_secret
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

